name: Myrtha 
  
on: 
  push:
  workflow_dispatch:

jobs:
  generate-spec:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hwcicd/myrtha:latest
    steps:
    - uses: actions/checkout@v4
    - run: make
    - uses: actions/upload-artifact@v4
      with:
        name: value_change_dump
        path: testbench.vcd
